[package]
name = "vfio_motion_common"
version = "0.1.0"
authors = ["dev <jackos1998@gmail.com>"]

[dependencies]
quick-error = "~1.2"
log = "~0.4"
virt = "~0.2"
libc = "0.2"
serde = "~1.0"
serde_json = "~1.0"
